### ISSUE TITLE
No display

### ISSUE THREAD

**Issue by theucanes** [adarhef/NowPlaying#3]
This is probably user error, but I cannot for the life of my get the widget to actually display. Snips is working and showing the data, but it won't pull to the index. I've launched the html to see and it is blank. Again, I am sure I am missing something. Please help! Let me know what you need to troubleshoot. I do have the local file linked in OBS. 
![image](https://github.com/adarhef/NowPlaying/assets/96313383/edb3b67d-50fd-405a-9110-5ab207a19fa0)

![image](https://github.com/adarhef/NowPlaying/assets/96313383/f62a56eb-f0f2-4040-acc8-07fac00871f2)

**Comment by theucanes** [comment]
![image](https://github.com/adarhef/NowPlaying/assets/96313383/ec1c7f64-fb0a-4e80-9dba-5a6fceda8b1e)

**Comment by adarhef** [comment]
Hey!
Would be easier to debug this by chatting on Discord or something, I don't immediately see the issue from what you shared so far. I'd need to dig in and refresh my memory.
My Discord username is `REDACTED`, hit me up there and I'll try to help.

**Comment by theucanes** [comment]
Sent you a message. Let me know when you are around! Thanks for the message.

**Comment by adarhef** [comment]
Follow up for the casual reader:
It's important to download the release from the Releases page and not the code itself, because it's in a pre-compiled state.
Also if you can download Snip separately and replace the current Snip folder with the new one you might be able to get over a few issues with the currently-shipping Snip.
